### PR TITLE
Extract compilation-related code into its own CompilationWorker

### PR DESCRIPTION
**Pull request by romac**
This change enables running various operations (such as Git commands) while the code is still compiling.

### CODE REVIEW

**Comment by MikaelMayer** [comment]
That's great already ! Will you work also on this branch to add mutiple compilation workers or can I already merge it?

**Comment by romac** [comment]
@MikaelMayer I won't have much time to work more on this until February, so I would say let's merge it already. Feel free to let me know if you run into any bugs.

By the way, I haven't been able to reproduce the bug we ran into the other day, where the Git commit window would stay empty. Feel free to let me know as well if you still have a problem with after these changes.

**Comment by MikaelMayer** [comment]
Sorry to inform you of a big bug, @romac
Open a file in leon-web (local or online). Put a compilation error into it. Wait for compilation.
Remove the error. The compilation error is still returned. Compilations errors seem now to stack instead of disappearing.
Can you please fix that asap?

**Comment by romac** [comment]
@MikaelMayer Fixed in #24

**Pull request merged**
